### ISSUE TITLE
Razlicite valute

### ISSUE THREAD

**Issue by ivanazuzic** [Svebor1/Spendiverse#19]

**Comment by ivanazuzic** [comment]
https://stackoverflow.com/questions/15591768/add-more-space-between-items-in-android-spinner-without-custom-style

**Comment by Svebor1** [comment]
78081b68539b4b1c06d60d7d97841b4e092db926

**Comment by Svebor1** [comment]
c41487df0f5a64f5432aca7adf26649f9f1b7c94

**Comment by Svebor1** [comment]
f6917f5c82bf32ae222d13ced9c394d79f73b247

**Comment by Svebor1** [comment]
147ba1463a325ca63db92927b85c3b3f0455ad1b

**Comment by Svebor1** [comment]
ea9c86a3320c3434f93865a019dd65017de0998e

**Comment by Svebor1** [comment]
e0d9273eccb16ce0c30be545b82cc6ee0a9bf55b

**Comment by Svebor1** [comment]
1e6cbf7c5bca20dcc136e9211b02e479fda99aa8
