### ISSUE TITLE
Preračunavanje valuta za 2. verziju aplikacije

### ISSUE THREAD

**Issue by Svebor1** [Svebor1/Spendiverse#7]
Potrebno je osmisliti i napraviti preračunavanje valuta, kako raditi grafove za valute i najbolji način snalažanja između valuta.

**Comment by ivanazuzic** [comment]
https://medium.com/swlh/how-i-built-a-simple-currency-converter-app-using-recommended-android-pattern-and-architecture-204a3bbfc142
